# Generated by Django 6.0.5 on 2026-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicapp', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
    ]
